/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/articles/': RouteRecordInfo<
      '/articles/',
      '/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit-logs/': RouteRecordInfo<
      '/audit-logs/',
      '/audit-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/bootstrap'
      | '/auth/forgot-password'
      | '/auth/reset-password'
      | '/auth/sign-in'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/bootstrap': RouteRecordInfo<
      '/auth/bootstrap',
      '/auth/bootstrap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comments/': RouteRecordInfo<
      '/comments/',
      '/comments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/[code]'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/[code]': RouteRecordInfo<
      '/errors/[code]',
      '/errors/:code',
      { code: ParamValue<true> },
      { code: ParamValue<false> },
      | never
    >,
    '/galleries/': RouteRecordInfo<
      '/galleries/',
      '/galleries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/journals/': RouteRecordInfo<
      '/journals/',
      '/journals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logs/': RouteRecordInfo<
      '/logs/',
      '/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media/': RouteRecordInfo<
      '/media/',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navigation/': RouteRecordInfo<
      '/navigation/',
      '/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pages/': RouteRecordInfo<
      '/pages/',
      '/pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/ai': RouteRecordInfo<
      '/settings/ai',
      '/settings/ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/email': RouteRecordInfo<
      '/settings/email',
      '/settings/email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/integrations': RouteRecordInfo<
      '/settings/integrations',
      '/settings/integrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/site': RouteRecordInfo<
      '/settings/site',
      '/settings/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/articles/index.vue': {
      routes:
        | '/articles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/audit-logs/index.vue': {
      routes:
        | '/audit-logs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/bootstrap'
        | '/auth/forgot-password'
        | '/auth/reset-password'
        | '/auth/sign-in'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/bootstrap.vue': {
      routes:
        | '/auth/bootstrap'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories/index.vue': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comments/index.vue': {
      routes:
        | '/comments/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/[code]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/[code].vue': {
      routes:
        | '/errors/[code]'
      views:
        | never
      pathParamNames:
        | 'code'
    }
    'src/pages/galleries/index.vue': {
      routes:
        | '/galleries/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/journals/index.vue': {
      routes:
        | '/journals/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/links/index.vue': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/logs/index.vue': {
      routes:
        | '/logs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/media/index.vue': {
      routes:
        | '/media/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/navigation/index.vue': {
      routes:
        | '/navigation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pages/index.vue': {
      routes:
        | '/pages/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/ai.vue': {
      routes:
        | '/settings/ai'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/email.vue': {
      routes:
        | '/settings/email'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/integrations.vue': {
      routes:
        | '/settings/integrations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/site.vue': {
      routes:
        | '/settings/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tags/index.vue': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
