ALTER TABLE articles
    ADD COLUMN version bigint NOT NULL DEFAULT 1 CHECK (version > 0);

ALTER TABLE articles
    ADD CONSTRAINT articles_published_content_check CHECK (
        status <> 'published'
        OR (
            btrim(title) <> ''
            AND btrim(slug::text) <> ''
            AND btrim(markdown_source) <> ''
            AND btrim(rendered_html) <> ''
            AND published_at IS NOT NULL
        )
    );

CREATE INDEX articles_updated_idx
    ON articles (updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX article_tags_tag_idx ON article_tags (tag_id, article_id);

CREATE TABLE article_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    revision_no bigint NOT NULL CHECK (revision_no > 0),
    markdown_source text NOT NULL,
    metadata_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    operator_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (article_id, revision_no)
);

CREATE INDEX article_revisions_article_idx
    ON article_revisions (article_id, revision_no DESC);
