-- Phase 08 第一批：AI 编辑器助手 + 评论 AI 审核（不含 Embedding/RAG/Semantic Search）
-- setting_groups 增加 ai 分组；新增 ai_requests 审计表；comments 增加 AI 审核结论列。

-- ============================================================
-- 1. setting_groups：增加 ai 分组
-- ============================================================
ALTER TABLE setting_groups
    DROP CONSTRAINT IF EXISTS setting_groups_grp_check;

ALTER TABLE setting_groups
    ADD CONSTRAINT setting_groups_grp_check
    CHECK (grp IN ('appearance', 'email', 'integrations', 'ai'));

-- 预插默认值，保证 GET 永远命中
INSERT INTO setting_groups (grp) VALUES ('ai');

-- ============================================================
-- 2. AI 请求审计表
-- ============================================================
CREATE TABLE ai_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 功能标识：editor_rewrite / editor_summary / editor_metadata / comment_moderation
    feature text NOT NULL
        CHECK (feature IN ('editor_rewrite', 'editor_summary', 'editor_metadata', 'comment_moderation')),
    -- 操作者；评论自动审核等系统触发为空
    operator_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    model text NOT NULL DEFAULT '',
    status text NOT NULL CHECK (status IN ('success', 'failed', 'cancelled')),
    prompt_tokens integer,
    completion_tokens integer,
    latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
    -- 失败分类（timeout / rate_limited / provider / invalid_output），不存原始错误细节
    error_category text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ai_requests_feature_created_idx ON ai_requests (feature, created_at DESC);
CREATE INDEX ai_requests_operator_created_idx ON ai_requests (operator_user_id, created_at DESC);

-- ============================================================
-- 3. comments：AI 审核结论（仅展示与标记，不自动 approve/delete）
-- ============================================================
ALTER TABLE comments
    ADD COLUMN ai_risk text CHECK (ai_risk IN ('safe', 'suspicious', 'spam'));

ALTER TABLE comments
    ADD COLUMN ai_reason text;

ALTER TABLE comments
    ADD COLUMN ai_confidence real;
