CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username citext NOT NULL UNIQUE,
    email citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    display_name text NOT NULL,
    avatar_url text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint REFERENCES categories(id) ON DELETE RESTRICT,
    kind text NOT NULL DEFAULT 'article' CHECK (kind IN ('article', 'link', 'gallery')),
    name text NOT NULL,
    slug citext NOT NULL,
    description text NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    UNIQUE (kind, slug)
);

CREATE TABLE articles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'recycled')),
    slug citext NOT NULL UNIQUE,
    title text NOT NULL,
    summary text NOT NULL DEFAULT '',
    cover_url text,
    markdown_source text NOT NULL,
    rendered_html text NOT NULL,
    seo_keywords text[] NOT NULL DEFAULT '{}',
    access_password_hash text,
    allow_comments boolean NOT NULL DEFAULT true,
    is_pinned boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    comment_count bigint NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
    visit_count bigint NOT NULL DEFAULT 0 CHECK (visit_count >= 0),
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK (status <> 'published' OR published_at IS NOT NULL)
);

CREATE INDEX articles_listing_idx
    ON articles (status, is_pinned DESC, sort_order, published_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX articles_category_idx ON articles (category_id) WHERE deleted_at IS NULL;

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name citext NOT NULL UNIQUE,
    slug citext NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE article_tags (
    article_id bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, tag_id)
);

