CREATE TABLE media_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL CHECK (provider IN ('local', 's3', 'legacy_url')),
    object_key text NOT NULL UNIQUE,
    url text NOT NULL,
    original_name text NOT NULL,
    mime text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    width int,
    height int,
    sha256 text NOT NULL,
    alt text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted')),
    uploaded_by bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE INDEX media_assets_status_created_idx ON media_assets (status, created_at DESC);
CREATE INDEX media_assets_sha256_idx ON media_assets (sha256);

CREATE TABLE media_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    target_type text NOT NULL CHECK (target_type IN ('article_cover', 'article_content', 'gallery_item')),
    target_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (asset_id, target_type, target_id)
);

CREATE INDEX media_usages_target_idx ON media_usages (target_type, target_id);

CREATE TABLE background_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('media_cleanup', 'import_markdown', 'metadata_probe')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'done', 'failed')),
    attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts int NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
    run_at timestamptz NOT NULL DEFAULT now(),
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX background_jobs_status_run_at_idx ON background_jobs (status, run_at);

CREATE TABLE site_settings (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    site_name text NOT NULL DEFAULT 'Aries Next',
    site_description text NOT NULL DEFAULT '',
    site_url text NOT NULL DEFAULT '',
    logo_url text NOT NULL DEFAULT '',
    icp_text text NOT NULL DEFAULT '',
    default_cover_url text NOT NULL DEFAULT '',
    page_size_index int NOT NULL DEFAULT 10 CHECK (page_size_index > 0),
    page_size_archive int NOT NULL DEFAULT 10 CHECK (page_size_archive > 0),
    page_size_search int NOT NULL DEFAULT 10 CHECK (page_size_search > 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO site_settings (id) VALUES (1);
