-- Phase 06：扩展内容与外观设置
-- 新增 pages、journals、galleries、gallery_items、links、navigation_items、setting_groups 表。
-- categories 表已有 kind（article/link/gallery）与 UNIQUE (kind, slug)，本迁移不改表。

-- ============================================================
-- 1. 自定义页面（Markdown Page）
-- ============================================================
CREATE TABLE pages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 页面路径标识；软删除允许同名 slug 重建，故唯一约束用部分索引实现
    slug citext NOT NULL,
    title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
    content_markdown text NOT NULL DEFAULT '',
    content_html text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    sort_order integer NOT NULL DEFAULT 0,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX pages_slug_key ON pages (slug) WHERE deleted_at IS NULL;
CREATE INDEX pages_status_sort_idx ON pages (status, sort_order, id) WHERE deleted_at IS NULL;

-- ============================================================
-- 2. 日志（短内容 Timeline）
-- ============================================================
CREATE TABLE journals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_markdown text NOT NULL CHECK (char_length(content_markdown) BETWEEN 1 AND 2000),
    content_html text NOT NULL DEFAULT '',
    -- private 内容不得出现在任何 Public API / Sitemap / RSS
    visibility text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE INDEX journals_visibility_created_idx
    ON journals (visibility, created_at DESC)
    WHERE deleted_at IS NULL;

-- ============================================================
-- 3. 图库与图库条目
-- ============================================================
CREATE TABLE galleries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 图库分类为 categories 中 kind = 'gallery' 的行；删除受限防止产生悬空图库
    category_id bigint NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    slug citext NOT NULL,
    title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
    description text NOT NULL DEFAULT '',
    -- 封面只是展示引用，媒体删除时置空而非阻塞
    cover_media_id bigint REFERENCES media_assets(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX galleries_slug_key ON galleries (slug) WHERE deleted_at IS NULL;
CREATE INDEX galleries_category_idx ON galleries (category_id) WHERE deleted_at IS NULL;

CREATE TABLE gallery_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id bigint NOT NULL REFERENCES galleries(id) ON DELETE CASCADE,
    -- 媒体资产删除受限：仍需先解除引用，避免图库出现坏图
    media_asset_id bigint NOT NULL REFERENCES media_assets(id) ON DELETE RESTRICT,
    alt text NOT NULL DEFAULT '',
    location text NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- 同一媒体在同一图库中只出现一次
    UNIQUE (gallery_id, media_asset_id)
);

CREATE INDEX gallery_items_gallery_idx ON gallery_items (gallery_id, sort_order, id);

-- ============================================================
-- 4. 友情链接
-- ============================================================
CREATE TABLE links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 友链分类为 categories 中 kind = 'link' 的行，可空（允许未分类）；
    -- 应用层删除分类前检查未删除引用（409）；FK 用 SET NULL 是因为友链为软删除，
    -- RESTRICT 会让物理删除分类永远被回收站中的友链行阻塞
    category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
    title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 100),
    url text NOT NULL CHECK (char_length(url) BETWEEN 1 AND 2048),
    icon_url text CHECK (char_length(icon_url) <= 2048),
    description text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE INDEX links_category_sort_idx
    ON links (category_id, sort_order, id)
    WHERE deleted_at IS NULL;

-- ============================================================
-- 5. 导航菜单（最多两级，由应用层保证）
-- ============================================================
CREATE TABLE navigation_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 自引用父节点；删除受限防止子菜单悬空，两级限制由应用层校验
    parent_id bigint REFERENCES navigation_items(id) ON DELETE RESTRICT,
    label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 60),
    target_type text NOT NULL CHECK (target_type IN ('article', 'page', 'category', 'url')),
    -- 内部目标仅存 id，URL 目标仅存 url；二者互斥由下方 CHECK 保证
    target_id bigint,
    url text CHECK (char_length(url) <= 2048),
    open_in_new_tab boolean NOT NULL DEFAULT false,
    visible boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((target_type = 'url' AND url IS NOT NULL) OR (target_type <> 'url' AND target_id IS NOT NULL))
);

CREATE INDEX navigation_items_parent_sort_idx ON navigation_items (parent_id, sort_order, id);

-- ============================================================
-- 6. 设置分组（appearance / email / integrations）
-- ============================================================
CREATE TABLE setting_groups (
    grp text PRIMARY KEY CHECK (grp IN ('appearance', 'email', 'integrations')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- 乐观锁版本号：更新时 WHERE version = 期望值，冲突即拒绝
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- 预插三组默认值，保证 GET 永远命中
INSERT INTO setting_groups (grp) VALUES ('appearance'), ('email'), ('integrations');
