-- 运行日志体系：server_logs 承载 tracing 事件的批量落库。
-- 运行日志属可丢弃数据：不加 status/软删除，保留期到物理 DELETE（由写入方定时清理）。

CREATE TABLE server_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts timestamptz NOT NULL,
    -- 级别原文（ERROR/WARN/INFO/DEBUG/TRACE），不做 CHECK：未来新增级别无需改表
    level text NOT NULL,
    -- tracing target（模块路径）
    target text NOT NULL,
    message text NOT NULL,
    -- 最近 Span 名与请求 ID（HTTP 请求内日志可关联 TraceLayer Span）
    span_name text,
    request_id text,
    -- 事件的其余结构化字段
    fields jsonb NOT NULL DEFAULT '{}'
);

CREATE INDEX server_logs_ts_idx ON server_logs (ts DESC);
CREATE INDEX server_logs_level_ts_idx ON server_logs (level, ts DESC);
CREATE INDEX server_logs_target_ts_idx ON server_logs (target, ts DESC);
