-- Phase 05：评论系统与 Dashboard 聚合支持
-- 新增 comments、email_deliveries 表，扩展 site_settings 评论策略字段。

-- ============================================================
-- 1. 评论表
-- ============================================================
CREATE TABLE comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 评论目标：article / page / link（Phase 06 扩展）
    target_type text NOT NULL CHECK (target_type IN ('article', 'page', 'link')),
    target_id bigint NOT NULL,
    -- 评论层级：root_id 指向根评论，parent_id 指向直接父评论
    -- 根评论的 root_id = 自身 id，parent_id = NULL
    root_id bigint REFERENCES comments(id) ON DELETE CASCADE,
    parent_id bigint REFERENCES comments(id) ON DELETE CASCADE,
    -- 评论者信息
    author_name text NOT NULL CHECK (char_length(author_name) BETWEEN 1 AND 60),
    author_email text NOT NULL CHECK (char_length(author_email) BETWEEN 1 AND 254),
    author_url text CHECK (char_length(author_url) <= 2048),
    -- 内容
    content_markdown text NOT NULL CHECK (char_length(content_markdown) BETWEEN 1 AND 2000),
    content_html text NOT NULL DEFAULT '',
    -- 状态与审核
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected', 'spam', 'recycled')),
    moderator_id bigint REFERENCES users(id) ON DELETE SET NULL,
    moderated_at timestamptz,
    moderation_reason text CHECK (char_length(moderation_reason) <= 500),
    -- 隐私字段：只存 Hash/Digest，不存原始值
    ip_hash text NOT NULL DEFAULT '',
    user_agent_digest text NOT NULL DEFAULT '',
    -- 是否为管理员回复
    is_admin_reply boolean NOT NULL DEFAULT false,
    -- 时间
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

-- 目标查询索引：按 target 拉取已批准评论（Public API 核心查询路径）
CREATE INDEX comments_target_status_idx
    ON comments (target_type, target_id, status, created_at)
    WHERE deleted_at IS NULL;

-- 根评论下的回复查询
CREATE INDEX comments_root_idx
    ON comments (root_id, created_at)
    WHERE deleted_at IS NULL AND root_id IS NOT NULL;

-- 管理端筛选索引
CREATE INDEX comments_status_created_idx
    ON comments (status, created_at DESC)
    WHERE deleted_at IS NULL;

-- 重复提交检查：同 email + target 的时间窗口查询
CREATE INDEX comments_email_target_idx
    ON comments (author_email, target_type, target_id, created_at DESC);

-- ============================================================
-- 2. 邮件发送记录表
-- ============================================================
CREATE TABLE email_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 关联评论（可为空，系统通知可能不关联评论）
    comment_id bigint REFERENCES comments(id) ON DELETE SET NULL,
    recipient_email text NOT NULL,
    subject text NOT NULL,
    template text NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'failed', 'bounced')),
    attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts int NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX email_deliveries_status_idx
    ON email_deliveries (status, created_at);

-- ============================================================
-- 3. 扩展 site_settings：评论策略字段
-- ============================================================
ALTER TABLE site_settings
    ADD COLUMN comment_policy text NOT NULL DEFAULT 'moderated'
        CHECK (comment_policy IN ('closed', 'moderated', 'auto_approve'));

ALTER TABLE site_settings
    ADD COLUMN comments_per_page int NOT NULL DEFAULT 20
        CHECK (comments_per_page BETWEEN 5 AND 100);

-- ============================================================
-- 4. background_jobs 扩展：新增评论通知任务类型
-- ============================================================
ALTER TABLE background_jobs
    DROP CONSTRAINT IF EXISTS background_jobs_kind_check;

ALTER TABLE background_jobs
    ADD CONSTRAINT background_jobs_kind_check
    CHECK (kind IN ('media_cleanup', 'import_markdown', 'metadata_probe', 'comment_notification'));
