-- AI 能力二期：AI 导读 + 可开关的 AI 检索（相关文章 / 对话式搜索）。
-- AI 检索默认关闭（setting_groups.ai payload 的 smart_search 开关，默认 false），
-- 本 migration 只建结构，不启用任何行为；embedding 维度不固定，兼容不同模型。

-- ============================================================
-- 1. articles：AI 导读（发布时存库，前台文章页展示）
-- ============================================================
ALTER TABLE articles
    ADD COLUMN ai_brief text;

-- ============================================================
-- 2. ai_requests.feature：新功能枚举
-- ============================================================
ALTER TABLE ai_requests
    DROP CONSTRAINT IF EXISTS ai_requests_feature_check;

ALTER TABLE ai_requests
    ADD CONSTRAINT ai_requests_feature_check
    CHECK (feature IN (
        'editor_rewrite', 'editor_summary', 'editor_metadata', 'comment_moderation',
        'editor_tags', 'ai_brief', 'search_ask'
    ));

-- ============================================================
-- 3. background_jobs.kind：文章 embedding 任务
-- ============================================================
ALTER TABLE background_jobs
    DROP CONSTRAINT IF EXISTS background_jobs_kind_check;

ALTER TABLE background_jobs
    ADD CONSTRAINT background_jobs_kind_check
    CHECK (kind IN (
        'media_cleanup', 'import_markdown', 'metadata_probe', 'comment_notification',
        'article_embed'
    ));

-- ============================================================
-- 4. 文章内容块与向量
-- ============================================================
-- 文章分块与向量：一篇文章多个 chunk，replace_chunks 事务删旧插新。
-- embedding 使用内置 real[] 而非 pgvector：不依赖扩展（Windows/容器部署零额外组件），
-- 个人博客语料量小，余弦距离在应用层计算足够快。
CREATE TABLE article_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL CHECK (chunk_index >= 0),
    heading text NOT NULL DEFAULT '',
    content text NOT NULL,
    embedding real[],
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX article_chunks_article_chunk_idx
    ON article_chunks (article_id, chunk_index);

CREATE INDEX article_chunks_article_idx ON article_chunks (article_id);
